### ISSUE TITLE
Some changelists don't have a place_id

### ISSUE THREAD

**Issue by ekalvi** [locl-interactive/slack-loclbot#38]
```shell
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/erikkalviainen/code/slack-loclbot/rtmbot.py", line 50, in run
    self.input(reply)
  File "/Users/erikkalviainen/code/slack-loclbot/rtmbot.py", line 76, in input
    plugin.do(function_name, data)
  File "/Users/erikkalviainen/code/slack-loclbot/rtmbot.py", line 142, in do
    eval("self.module." + function_name)(data)
  File "/Users/erikkalviainen/code/slack-loclbot/plugins/loclbot.py", line 19, in process_message
    output = loclbot.process_message(data)
  File "/Users/erikkalviainen/code/slack-loclbot/services/locl.py", line 143, in process_message
    # are we connected to a business?
  File "/Users/erikkalviainen/code/slack-loclbot/services/locl.py", line 162, in _message_business
    def _message_business(self, place_id, text):
  File "/Users/erikkalviainen/code/slack-loclbot/services/locl.py", line 116, in process_changelist
    place_id = changelist["place_id"]
KeyError: 'changes'
```

**Comment by ekalvi** [comment]
Can't repro. Likely fixed in subsequent refactors.
